"""jobs, attempts, events, validations

Revision ID: 0003
Revises: 0002
Create Date: 2026-08-29 00:00:00.000000
"""

from __future__ import annotations

import sqlalchemy as sa
import weightsdb
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0003"
down_revision: str | None = "0002"
branch_labels: str | tuple[str, ...] | None = None
depends_on: str | tuple[str, ...] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "jobs",
        sa.Column("id", sa.String(length=26), nullable=False),
        sa.Column("task_profile_id", sa.String(), nullable=False),
        sa.Column("task_profile_version", sa.String(), nullable=False),
        sa.Column("class", sa.String(), nullable=False),
        sa.Column("base_priority", sa.Integer(), nullable=False),
        sa.Column("effective_priority", sa.Integer(), nullable=False),
        sa.Column("source", sa.String(), nullable=False),
        sa.Column("state", sa.String(), nullable=False),
        sa.Column("state_reason", sa.String(), nullable=True),
        sa.Column("idempotency_key", sa.String(), nullable=True),
        sa.Column("idempotent", sa.Boolean(), nullable=False),
        sa.Column("idempotency_expires_at", weightsdb.UtcDateTime(), nullable=True),
        sa.Column("request_json", weightsdb.PortableJSON(), nullable=True),
        sa.Column("prompt_hash", sa.String(), nullable=True),
        sa.Column("prompt_text", sa.String(), nullable=True),
        sa.Column("response_hash", sa.String(), nullable=True),
        sa.Column("response_text", sa.String(), nullable=True),
        sa.Column("structured_output_json", weightsdb.PortableJSON(), nullable=True),
        sa.Column("tool_calls_json", weightsdb.PortableJSON(), nullable=True),
        sa.Column("reasoning_available", sa.Boolean(), nullable=False),
        sa.Column("reasoning_summary", sa.String(), nullable=True),
        sa.Column("reasoning_source", sa.String(), nullable=True),
        sa.Column("selected_model_id", sa.String(length=26), nullable=True),
        sa.Column("runtime_profile_id", sa.String(length=26), nullable=True),
        sa.Column("runtime_profile_hash", sa.String(), nullable=True),
        sa.Column("served_context", sa.Integer(), nullable=True),
        sa.Column("served_context_source", sa.String(), nullable=True),
        sa.Column("target_gpu_index", sa.Integer(), nullable=True),
        sa.Column("attempt", sa.Integer(), nullable=False),
        sa.Column("max_attempts", sa.Integer(), nullable=False),
        sa.Column("lease_owner", sa.String(), nullable=True),
        sa.Column("lease_expires_at", weightsdb.UtcDateTime(), nullable=True),
        sa.Column("cancel_requested", sa.Boolean(), nullable=False),
        sa.Column("created_at", weightsdb.UtcDateTime(), nullable=False),
        sa.Column("scheduled_for", weightsdb.UtcDateTime(), nullable=True),
        sa.Column("queued_at", weightsdb.UtcDateTime(), nullable=True),
        sa.Column("started_at", weightsdb.UtcDateTime(), nullable=True),
        sa.Column("completed_at", weightsdb.UtcDateTime(), nullable=True),
        sa.Column("max_wait_seconds", sa.Integer(), nullable=True),
        sa.Column("queue_wait_ms", sa.Integer(), nullable=True),
        sa.Column("provider_ms", sa.Integer(), nullable=True),
        sa.Column("loadcoach_overhead_ms", sa.Integer(), nullable=True),
        sa.Column("total_ms", sa.Integer(), nullable=True),
        sa.Column("ttft_ms", sa.Integer(), nullable=True),
        sa.Column("input_tokens", sa.Integer(), nullable=True),
        sa.Column("output_tokens", sa.Integer(), nullable=True),
        sa.Column("thinking_tokens", sa.Integer(), nullable=True),
        sa.Column("validation_passed", sa.Boolean(), nullable=True),
        sa.Column("degradations_json", weightsdb.PortableJSON(), nullable=True),
        sa.Column("error_code", sa.String(), nullable=True),
        sa.Column("error_text", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["runtime_profile_id"],
            ["runtime_profiles.id"],
            name=op.f("fk_jobs_runtime_profile_id_runtime_profiles"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["selected_model_id"],
            ["models.id"],
            name=op.f("fk_jobs_selected_model_id_models"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_jobs")),
        sa.UniqueConstraint(
            "source", "idempotency_key", name=op.f("uq_jobs_source_idempotency_key")
        ),
    )
    op.create_index("ix_jobs_lease_expires_at", "jobs", ["lease_expires_at"], unique=False)
    op.create_index(
        "ix_jobs_selected_model_id_created_at",
        "jobs",
        ["selected_model_id", "created_at"],
        unique=False,
    )
    op.create_index(
        "ix_jobs_state_effective_priority_created_at",
        "jobs",
        ["state", "effective_priority", "created_at"],
        unique=False,
    )
    op.create_index("ix_jobs_state_queued_at", "jobs", ["state", "queued_at"], unique=False)
    op.create_index(
        "ix_jobs_task_profile_id_created_at",
        "jobs",
        ["task_profile_id", "created_at"],
        unique=False,
    )
    op.create_table(
        "job_attempts",
        sa.Column("id", sa.String(length=26), nullable=False),
        sa.Column("job_id", sa.String(length=26), nullable=False),
        sa.Column("attempt", sa.Integer(), nullable=False),
        sa.Column("model_id", sa.String(length=26), nullable=True),
        sa.Column("runtime_profile_hash", sa.String(), nullable=True),
        sa.Column("rank", sa.Integer(), nullable=True),
        sa.Column("started_at", weightsdb.UtcDateTime(), nullable=False),
        sa.Column("completed_at", weightsdb.UtcDateTime(), nullable=True),
        sa.Column("outcome", sa.String(), nullable=False),
        sa.Column("provider_ms", sa.Integer(), nullable=True),
        sa.Column("ttft_ms", sa.Integer(), nullable=True),
        sa.Column("input_tokens", sa.Integer(), nullable=True),
        sa.Column("output_tokens", sa.Integer(), nullable=True),
        sa.Column("finish_reason", sa.String(), nullable=True),
        sa.Column("error_code", sa.String(), nullable=True),
        sa.Column("error_text", sa.String(), nullable=True),
        sa.Column("partial_response_hash", sa.String(), nullable=True),
        sa.Column("prompt_id", sa.String(), nullable=True),
        sa.Column("prompt_version", sa.String(), nullable=True),
        sa.Column("prompt_sha256", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["job_id"], ["jobs.id"], name=op.f("fk_job_attempts_job_id_jobs"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["model_id"],
            ["models.id"],
            name=op.f("fk_job_attempts_model_id_models"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_job_attempts")),
        sa.UniqueConstraint("job_id", "attempt", name=op.f("uq_job_attempts_job_id_attempt")),
    )
    op.create_index(op.f("ix_job_attempts_job_id"), "job_attempts", ["job_id"], unique=False)
    op.create_table(
        "job_events",
        sa.Column("id", sa.String(length=26), nullable=False),
        sa.Column("job_id", sa.String(length=26), nullable=False),
        sa.Column("sequence", sa.Integer(), nullable=False),
        sa.Column("timestamp", weightsdb.UtcDateTime(), nullable=False),
        sa.Column("event_type", sa.String(), nullable=False),
        sa.Column("message", sa.String(), nullable=True),
        sa.Column("data_json", weightsdb.PortableJSON(), nullable=True),
        sa.ForeignKeyConstraint(
            ["job_id"], ["jobs.id"], name=op.f("fk_job_events_job_id_jobs"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_job_events")),
        sa.UniqueConstraint("job_id", "sequence", name=op.f("uq_job_events_job_id_sequence")),
    )
    op.create_index(op.f("ix_job_events_job_id"), "job_events", ["job_id"], unique=False)
    op.create_table(
        "validations",
        sa.Column("id", sa.String(length=26), nullable=False),
        sa.Column("job_attempt_id", sa.String(length=26), nullable=False),
        sa.Column("kind", sa.String(), nullable=False),
        sa.Column("passed", sa.Boolean(), nullable=False),
        sa.Column("detail_json", weightsdb.PortableJSON(), nullable=True),
        sa.Column("duration_ms", sa.Integer(), nullable=True),
        sa.Column("created_at", weightsdb.UtcDateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["job_attempt_id"],
            ["job_attempts.id"],
            name=op.f("fk_validations_job_attempt_id_job_attempts"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_validations")),
    )
    op.create_index(
        op.f("ix_validations_job_attempt_id"), "validations", ["job_attempt_id"], unique=False
    )
    # Batch mode, not a bare ALTER: SQLite cannot add a foreign key to an existing table, so
    # Alembic recreates it by copy-and-move. Autogenerate emits the bare form; this is the
    # adjustment its own "please adjust!" banner asks for.
    with op.batch_alter_table("routing_decisions", schema=None) as batch_op:
        batch_op.add_column(sa.Column("job_id", sa.String(length=26), nullable=True))
        batch_op.create_index("ix_routing_decisions_job_id", ["job_id"], unique=False)
        batch_op.create_foreign_key(
            op.f("fk_routing_decisions_job_id_jobs"),
            "jobs",
            ["job_id"],
            ["id"],
            ondelete="CASCADE",
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("routing_decisions", schema=None) as batch_op:
        batch_op.drop_constraint(op.f("fk_routing_decisions_job_id_jobs"), type_="foreignkey")
        batch_op.drop_index("ix_routing_decisions_job_id")
        batch_op.drop_column("job_id")
    op.drop_index(op.f("ix_validations_job_attempt_id"), table_name="validations")
    op.drop_table("validations")
    op.drop_index(op.f("ix_job_events_job_id"), table_name="job_events")
    op.drop_table("job_events")
    op.drop_index(op.f("ix_job_attempts_job_id"), table_name="job_attempts")
    op.drop_table("job_attempts")
    op.drop_index("ix_jobs_task_profile_id_created_at", table_name="jobs")
    op.drop_index("ix_jobs_state_queued_at", table_name="jobs")
    op.drop_index("ix_jobs_state_effective_priority_created_at", table_name="jobs")
    op.drop_index("ix_jobs_selected_model_id_created_at", table_name="jobs")
    op.drop_index("ix_jobs_lease_expires_at", table_name="jobs")
    op.drop_table("jobs")
    # ### end Alembic commands ###
